# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name .wcov
#'
#' @title Weighted Covariance Matrix
#'
#' @description \code{wcov} computes the estimates of the weighted covariance
#'  matrix and the weighted mean of the data.
#'
#' @param x A matrix with \eqn{m} columns and \eqn{n} rows, where each column
#'  represents a different variable and each row a different observation.
#'
#' @param w A non-negative and non-zero vector of weights for each observation.
#'  Its length must equal the number of rows of x.
#'
#' @return A list with two components:
#'  \itemize{
#'   \item \code{center}: an estimate for the center (mean) of the data.
#'   \item \code{cov}: the estimated (weighted) covariance matrix.
#'  }
#'
#' @author Simon Garnier, \email{garnier@@njit.edu}
#'
#' @examples
#' m <- matrix(c(rnorm(500, 6), rnorm(500, 11, 3)), ncol = 2)
#' w <- runif(500)
#' gravitree:::.wcov(m, w)
#'
.wcov <- function(x, w) {
    .Call('_wcec_wcov', PACKAGE = 'wcec', x, w)
}

